### ISSUE TITLE
App status

### ISSUE THREAD

**Issue by dantebarba** [davidcelis/SunPaper#8]
Hi,

I'm a user and supporter of this app since 2017. I'm planning on moving to an M1 mac. Is there any information about the compatibility or development? Looks like the app has been abandoned, it's no longer available in the App Store neither.

**Comment by davidcelis** [comment]
Yeah, I kinda gave up on developing the app when Apple released dynamic desktops, as that felt like a much better feature to me. Given I don't provide support, I made the decision to pull it from the app store as well. Sorry!

**Comment by dantebarba** [comment]
:(. Well but dynamic desktop doesnt allow you to change wallpapers. I really liked your app. I'll try to compile it to Big Sur, home its not too difficult.

**Comment by Joshfindit** [comment]
> Yeah, I kinda gave up on developing the app when Apple released dynamic desktops, as that felt like a much better feature to me. Given I don't provide support, I made the decision to pull it from the app store as well. Sorry!

Sad 😥
As mentioned, Apple only allows specific dynamic wallpapers and while it’s integrated and has a lot more “steps” between the different states, I actually don’t like how photoshopped they are and would be much happier having timelapses (either frame by frame video, or extracting frames and adding them to an app).

**Comment by davidcelis** [comment]
Believe me, I also wish Apple would allow the creation of custom dynamic desktops! Unfortunately, this app always had some issues for folks. I’d fairly frequently get emails from folks about the app being unable to find their location and not be able to debug why it won’t work for them when it works for most others. It’s a bit too hard for me to provide support here.

I don’t have an M1 mac to try compiling this on but if anybody can verify that it will still work, I’d be happy to just put it back up on the app store but for free with a notice that I can’t provide support.

**Comment by dantebarba** [comment]
It works with M1 Mac!. It runs under rosetta2 but runs flawless and doesn't seem to have much of an impact in battery life. Its really a great app. I've forked it and in the future I will try to compile it for Apple Silicon.

**Comment by davidcelis** [comment]
In that case I’m happy to leave it on the App Store. Sometime today or tomorrow, I’ll re-submit it and just make it free
